# perform linux build followed by the windows build in sequence
# 'fast_finish: true' will prevent the windows build from running if the linux build fails
# the windows build will trigger the release on success

image:
  - Ubuntu
  - Visual Studio 2017

environment:
  # semantic-version requires node > 8.3
  nodejs_version: 10.3.0
  GITHUB_TOKEN:
    secure: ujH3AA1wAzZqH288EDFxMdNhIM+oojkrEfT/avjGwc0naTizb5j3DFeHhRziAufy
  NUGET_TOKEN:
    secure: SEajLjSiDgLP9CnceSfR6zxshTq0O7GU8n1JUz2ncq3Gb2tb4AaOumad4YzYaGxz

install:
  - cmd: powershell Install-Product node $env:nodejs_version
  - sh: nvm install $nodejs_version

build_script:
  - ps: .\build.ps1

# Disable appveyor test discovery
test: off

# Disable builds on new tags
skip_tags: true

cache:
  # Cake packages cache (build.ps1 or build.cake)
  - tools -> build.*
  # NuGet packages cache (windows and linux)
  - '%LocalAppData%\NuGet\v3-cache -> **\*.csproj'
  - '$HOME/.local/share/NuGet/v3-cache -> **/*.csproj'

matrix:
  # Fail as soon as any job fails
  fast_finish: true
